config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      get '/responses', to: 'responses#index'
    end
  end
  
  resources :questions, only: [:new, :create, :show] do
    resources :responses, only: [:new, :create]
  end

  resources :taggings, only: [:create]

  get "/dashboard", to: "dashboard#index"
  get "/react-dashboard", to: "dashboard#react_dashboard"
  
  root to: 'questions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :responses

  validates :asker, presence: true
  validates :question, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :question

  has_many :taggings

  validates_presence_of :response, :responder
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :response

  validates_presence_of :tag
end

app/controllers/api/v1/responses_controller.rb
module Api::V1
  class ResponsesController < ApplicationController
    def index
      @recent_responses = Response.all.shuffle.take(2)

      render json: @recent_responses
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @lincoln_response_count = nil
    @banana_response_count = nil

    @recent_responses = Response.all.shuffle.take(2)
    @tagged_responses = nil
  end

  def react_dashboard
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params.require(:question).permit(:asker, :question))

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @response = question.responses.new
  end

  def create
    @response = question.responses.new(params.require(:response).permit(:responder, :response))

    if @response.save
      redirect_to question
    else
      render 'new'
    end
  end

  private

  def question
    Question.find(params[:question_id])
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  def create
    Tagging.create!(params.require(:tagging).permit(:response_id, :tag))

    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_response_card.html.erb
<div class="response-card">
  <h3><%= response.question.question %></h3>
  <p><strong>Responder: </strong><%= response.responder %></p>
  <p><strong>Response: </strong><%= response.response %></p>
  <p>Tags: insert tags here...</p> 

  <%= form_for response.taggings.new do |f| %>
    <%= f.hidden_field(:response_id, value: response.id) %>
    <div>
      <%= f.label(:tag, "Tag:") %>
      <%= f.text_field(:tag) %>
    </div>
    <button class="tag-submit" type="submit">Tag This Response</button>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<h2>Number of responses from Abraham Lincoln: <%= @lincoln_response_count %></h2>

<h2>Number of responses containing the word "banana" in them: <%= @banana_response_count %></h2>

<div class="grid">
  <div class="column">
    <h2>10 most recent responses</h2>
    <% @recent_responses.each do |response| %>
      <%= render("response_card", response: response)%>
    <% end %>
  </div>

  <div class="column">
    <h2>Tagged Responses</h2>
    <form action="">
      <input type="text" placeholder="tag name"/>
      <button type="submit">Search for responses</button>
    </form>
    
    <% @tagged_responses %>
  </div>
</div>

app/views/dashboard/react_dashboard.html.erb
<% content_for :js do %>
  <%= javascript_pack_tag 'react-dashboard' %>
<% end %>

<div id="react_dashboard"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Questions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <%= yield :js %>
  </body>
</html>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  <div>
    <%= f.label(:asker, "Who's asking?") %>
    <%= f.text_field(:asker) %>
  </div>

  <div>
    <%= f.label(:question, "What's the question?") %>
    <%= f.text_field(:question) %>
  </div>

  <div>
    <%= f.submit("Create Question") %>
  </div
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.asker %> is asking:</h1>
<p><%= @question.question%></p>

<p><%= link_to 'Add Your Response', new_question_response_path(@question)%></p>

app/views/responses/new.html.erb
<%= form_for @response, url: question_responses_path(@response.question) do |f| %>
  <div>
    <%= f.label(:responder, "Who's responding?") %>
    <%= f.text_field(:responder) %>
  </div>

  <div>
    <%= f.label(:response, @response.question.question) %>
    <%= f.text_field(:response) %>
  </div>

  <div>
    <%= f.submit("Submit Response") %>
  </div
<% end %>